### ISSUE TITLE
Event: 2018-05-09 (Lightning Talks)

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/events#11]
NOTE: This can be closed out once the Video Producer Checklist is completed.

## Roles

- Event Organizer: @frahugo 
- Host: @nicholasjhenry
- Community Advocate: @nicholasjhenry
- Videographer: @frahugo
- Video Producer: @frahugo

### Presentation - {presenter name}

- Presentation format (full, demi, lightning): {format}
- Title and description: {title}. {description}
- Your biography (1-2 sentences): {bio}
- Twitter handle: {twitter}
- Can the talk be recorded: {yes/no}
- Open to questions in the group: {yes/no}
- Adapter requirements for HDMI connection (if required): {yes/no}

## Program

- 18:30 Mingle: A chance to meet and chat with other Elixir enthusiasts before the presentations start. Grab a bite to eat.
- 19:00 Welcome and Community Updates by {name}: A review of points of interest in our local community and Elixir in general.
- 19:20 Lightning Talks!
- 20:20 Open Announcements: Would you like to introduce yourself to the group and what you hope to learn? Are you a company looking to hire an Elixir developer? Please share!
- 20:30 Finish: See you in {month}!

### ASAP before the event

- [x] Book the venue
- [x] Schedule talks
- [x] Identify sponsor
- [x] Apply for liquor permit: [Online Form](https://pes.securitepublique.gouv.qc.ca/acolyte/facettes/permis/captcha.faces?sid=0QJY03KP9RKWS)

###  Minus 2 weeks

- [ ] Determine agenda
- [x] Publish event on Meetup.com
- [x] Tweet the event

### Minus 1 week

- [x] Check with the speakers if they need anything
- [x] Check with the sponsors if for announcements
- [x] Request for bar server

### On the day of the event

Plan to be at the venue at 17:00 to be ready at 18:00

- [x] Request an update on RSVP's

> Hey, everybody, we're looking forward to seeing you tonight. If you're unable to make it, can you please update your RSVP as a "No". This will be a big help with planning. Hopefully, we'll see you in next month instead.

- [ ] Print [presentation checklist](https://github.com/montrealelixir/playbook/issues/18)

#### Food and Beverage

- [x] Order the food (http://www.pizzafco.com/contact/)  

  Order 1m pizzas. Ask them to slice it in 14. About 2 slices per person.
  Have it delivered to Shopify, 525 Ave Viger, Suite 300. The   delivery person will ask for the credit card that was used to pay the order.

  - Boscaiola
  - Margherita
  - Speck
  - Caprese
  - Diavola

- [x] Buy the drinks
  - 3 x 12 beer
  - 2 x 6 soda
  - 1 x 12 water
- [x] Bring the liquor permit

### During the event

- [ ] Display welcome slide with sponsors
- [ ] Put music on
- [ ] Display the liquor permit

### At the end of the event

- [ ] Take liquor permit back

### Plus 1 day

- [x] Write a follow-up on Meetup.com
- [x] A tweet of appreciation to sponsors
- [x] Email the sponsors to say thank you
- [x] Email the venue to say thank you
- [ ] Email the speakers to say thank you

### ASAP after the event

- [x] Review checklist from Playbook to incorporate new items
- [x] Create issue for next event

### Minus 1 week

- [ ] Prepare introduction notes
- [ ] Prepare community update

### During presentations

- [ ] Prepare backup questions
- [ ] Take photos of presenters
- [ ] Live tweet

### ASAP after the event

- [ ] Post photos to Meetup.com

### On the day of the event

- [ ] Prepare recording equipment
- [ ] Recharge camera batteries
- [ ] Make sure AA batteries are OK in the wireless audio modules

### Before the event starts

- [ ] Perform sound check (mic, camera, venue AV system)
- [ ] HDMI capture test (capture, then verify content on SD card)

### Before the presentation

- [ ] Install mic on presenter
- [ ] **IMPORTANT** make sure the cables are properly screwed to the receiver/transmitter units. Otherwise, you could loose the audio when the cable move.
- [ ] Sound check
- [ ] Start HDMI capturing
- [ ] Start video recording (make sure we have portion of the displayed slides so we can sync video with HDMI capturing)

### At the end of the event

- [ ] Pack equipment

### ASAP after the event

- [ ] Produce and publish videos
- [ ] Include links to slides on YouTube
- [ ] Announce videos on Twitter and Meetup.com

**Comment by remi** [comment]
* **Presentation format (full, demi, lightning):**
lightning

* **Title and description:**
Ecto Embedded Schemas. We’ll take a look at how Ecto’s embedded schemas can help us persist and retrieve structured and meaningful data using database JSON columns.

* **Your biography (1-2 sentences):**
Rémi Prévost is Web Development Lead at Mirego, in Quebec City. He enjoys writing code (Elixir & JavaScript) that powers beautiful applications.

* **Twitter handle:**
`@remi`

* **Can the talk be recorded:**
yes

* **Open to questions in the group:**
yes

* **Adapter requirements for HDMI connection (if required):**
no

**Comment by nicoespeon** [comment]
- **Presentation**
Nicolas Carlo

- **Presentation format (full, demi, lightning)**
Lightning 😉 

- **Title and description**
TDD with Elixir
I'm quite new to Elixir. I love practicing *Test Driven Development*. I'll share with you my findings, successes and pitfalls of doing TDD with Elixir.

- **Your biography (1-2 sentences)**
I'm a French web developer in love with *DD*-things as for TDD, BDD, DDD… I'm now working with awesome teammates at Busbud, in Montréal, enjoying life in Canada 🍁

- **Twitter handle**
@nicoespeon

- **Can the talk be recorded**
Yes

- **Open to questions in the group**
Yes

- **Adapter requirements for HDMI connection (if required)**
No, I'll push my slides online so we can access on your computer (if that's fine for you) 👍

**Comment by gcauchon** [comment]
- **Presentation**
Guillaume Cauchon

- **Format**
lightning

- **Title and description**

1. Debugging `elixir` efficiently
What are the tools available to build and diagnose your modules.

2. Understanding & monitoring your OTP app with `:observer`
A quick walkthrough of the features built-in this awesome tool Erlang!

- **Biography**
Guillaume is a web developer/architect at [Mirego](https://www.mirego.com) and the founder of [À la garderie](https://www.alagarderie.ca), a communication platform for daycares and early childhood centers. After many years of object oriented, he is now fully embracing the _functionnal_ state of mind and the `Elixir` stack/community.

- **Twitter**
@gcauchon

- **Can the talk be recorded?**
yes

- **Open to questions in the group?**
yes

- **Adapter requirements for HDMI connection?**
no

**Comment by bgracie** [comment]
* Presentation format (full, demi, lightning): lightning
* Title and description: An experiment in domain language planning  -- showing a tool meant to facilitate domain language planning with stakeholders in business apps
* Your biography (1-2 sentences)
Brian is a web developer migrating from Ruby on Rails to Elixir/Phoenix.  He loves the elegance of functional programming.
* Can the talk be recorded: yes
* Open to questions in the group: yes
* Adapter requirements for HDMI connection (if required): none
