### ISSUE TITLE
Event: 2019-07-10 [Cancelled]

### ISSUE THREAD

**Issue by frahugo** [montrealelixir/events#21]
## Roles

- Event Organizer: {name}
- Host: {name}
- Community Advocate: {name}
- Videographer: {name}
- Video Producer: {name}

### Presentation - Andy A

NOTE: More details to come, requested to have details posted to this issue.  

Presentation format (full, demi, lightning): Full
Title and description: Building an IoT Gateway in Elixir - Insights as a first-time adopter
Your biography (1-2 sentences): Worked for over 6 years on web based stacks (eg. Rails).  Using Elixir since Spring 2018 and recently deployed to production.
Twitter handle: N/A, LinkedIn? https://www.linkedin.com/in/andy-arrowsmith-43448635/
Can the talk be recorded: yes
Open to questions in the group: yes
Adapter requirements for HDMI connection (if required): normal HDMI

### Presentation - {presenter name}

- Presentation format (full, demi, lightning): {format}
- Title and description: {title}. {description}
- Your biography (1-2 sentences): {bio}
- Twitter handle: {twitter}
- Can the talk be recorded: {yes/no}
- Open to questions in the group: {yes/no}
- Adapter requirements for HDMI connection (if required): {yes/no}

## Program

- 18:30 Mingle: A chance to meet and chat with other Elixir enthusiasts before the presentations start. Grab a bite to eat.
- 19:00 Welcome
- 19:05 "Building an IoT Gateway in Elixir" by Andy A. Insights as a first-time adopter
- 19:50 Open Announcements: Would you like to introduce yourself to the group and what you hope to learn? Are you a company looking to hire an Elixir developer? Please share!
- 20:00 Finish: See you in September!

### ASAP before the event

- [x] Book the venue
- [x] Schedule talks
- [ ] Identify sponsor
- [ ] Apply for liquor permit: [Online Form](https://pes.securitepublique.gouv.qc.ca/acolyte/facettes/permis/captcha.faces?sid=0QJY03KP9RKWS)

###  Minus 2 weeks

- [x] Determine agenda
- [x] Publish event on Meetup.com
- [ ] Tweet the event

### Minus 1 week

- [ ] Check with the speakers if they need anything
- [ ] Check with the sponsors if for announcements
- [ ] Request for bar server

### On the day of the event

Plan to be at the venue at 17:00 to be ready at 18:00

- [x] Request an update on RSVP's

> Hey everybody, we're looking forward to seeing you tonight. If you're unable to make it, can you please update your RSVP as a "No". This will be a big help with planning. Hopefully, we'll see you next month :-)

- [ ] Print name tags
- [ ] Print [presentation checklist](https://github.com/montrealelixir/playbook/issues/18)

#### Food and Beverage

- [ ] Order the food (http://www.pizzafco.com/contact/)  

  Order 1m pizzas. Ask them to slice it in 14. About 2 slices per person.
  Have it delivered to Shopify, 525 Ave Viger, Suite 300. The   delivery person will ask for the credit card that was used to pay the order.

  - Boscaiola
  - Margherita
  - Speck
  - Caprese
  - Diavola

- [ ] Buy the drinks
  - 3 x 12 beer
  - 2 x 6 soda
  - 1 x 12 water
- [ ] Bring the liquor permit

### During the event

- [ ] Display welcome slide with sponsors
- [ ] Put music on
- [ ] Display the liquor permit

### At the end of the event

- [ ] Take liquor permit back

### Plus 1 day

- [ ] Write a follow-up on Meetup.com
- [ ] A tweet of appreciation to sponsors
- [ ] Email the sponsors to say thank you
- [ ] Email the venue to say thank you
- [ ] Email the speakers to say thank you

### ASAP after the event

- [ ] Review checklist from Playbook to incorporate new items
- [ ] Create issue for next event

### Minus 1 week

- [ ] Prepare introduction notes
- [ ] Prepare community update

### During presentations

- [ ] Prepare backup questions
- [ ] Take photos of presenters
- [ ] Live tweet

### ASAP after the event

- [ ] Post photos to Meetup.com

### On the day of the event

- [ ] Prepare recording equipment
- [ ] Recharge camera batteries
- [ ] Make sure AA batteries are OK in the wireless audio modules

### Before the event starts

- [ ] Perform sound check (mic, camera, venue AV system)
- [ ] HDMI capture test (capture, then verify content on SD card)

### Before the presentation

- [ ] Install mic on presenter
- [ ] **IMPORTANT** make sure the cables are properly screwed to the receiver/transmitter units. Otherwise, you could loose the audio when the cable move.
- [ ] Sound check
- [ ] Start HDMI capturing
- [ ] Start video recording (make sure we have portion of the displayed slides so we can sync video with HDMI capturing)

### At the end of the event

- [ ] Pack equipment

### ASAP after the event

- [ ] Produce and publish videos
- [ ] Include links to slides on YouTube
- Announce videos
  - [ ] [Twitter](https://twitter.com/montrealelixir)
  - [ ] [Meetup.com](https://www.meetup.com/montrealelixir/)
  - [ ] [ElixirForum](https://elixirforum.com/c/learning-resources/talks)

## Credits

The checklist is based on and inspired by [montreal.rb](https://github.com/montrealrb/playbook/blob/master/checklists/meetup.md).

**Comment by aarrowsmith** [comment]
Presentation format (full, demi, lightning): Full
Title and description: Building an IoT Gateway in Elixir - Insights as a first-time adopter
Your biography (1-2 sentences): Worked for over 6 years on web based stacks (eg. Rails).  Using Elixir since Spring 2018 and recently deployed to production.
Twitter handle: N/A, LinkedIn? https://www.linkedin.com/in/andy-arrowsmith-43448635/
Can the talk be recorded: yes
Open to questions in the group: yes
Adapter requirements for HDMI connection (if required): normal HDMI
